### ISSUE TITLE
Taking a single slice from a multidimensional dataset object

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#372]
Currently taking a single slice (reducing the rank) does not work it seems because of the transposition.

```
>>> dat = wt.data.from_PyCMDS(datasets.PyCMDS.wm_w2_w1_000)
>>> dat.signal_diff[5]
[5]
[5, slice(None, None, None)]
[5, slice(None, None, None), slice(None, None, None)]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    dat.signal_diff[5]
  File "/home/kyle/wright/wrighttools/WrightTools/data/_data.py", line 264, 
in __getitem__
    return h5py.Dataset.__getitem__(self, tuple(indices)).transpose(self.transposition)
ValueError: axes don't match array
>>> dat.signal_diff[5:6]
[slice(5, 6, None)]
[slice(5, 6, None), slice(None, None, None)]
[slice(5, 6, None), slice(None, None, None), slice(None, None, None)]
array([[[ 0.009239,  0.004176,  0.013995,  0.019234,  0.032105,  0.028571,
          0.057538,  0.067145,  0.053892,  0.035661,  0.038108],
        [ 0.006867,  0.012266,  0.013482,  0.022586,  0.034085,  0.049813,
          0.050865,  0.061698,  0.046345,  0.034705,  0.034251],
        [ 0.008093,  0.009485,  0.019699,  0.045316,  0.042605,  0.066759,
          0.068236,  0.061194,  0.056653,  0.044821,  0.034751],
        [ 0.011175,  0.01587 ,  0.032948,  0.042902,  0.058639,  0.081957,
          0.082119,  0.077104,  0.070681,  0.041672,  0.034173],
        [ 0.018048,  0.031793,  0.04394 ,  0.055542,  0.089813,  0.099888,
          0.099856,  0.097067,  0.079357,  0.05533 ,  0.049295],
        [ 0.029058,  0.041938,  0.071855,  0.0942  ,  0.13493 ,  0.149842,
          0.121066,  0.106902,  0.087081,  0.076938,  0.054789],
        [ 0.045941,  0.062734,  0.101896,  0.125014,  0.164143,  0.16488 ,
          0.159616,  0.126791,  0.105373,  0.084804,  0.065533],
        [ 0.069778,  0.0903  ,  0.113436,  0.152228,  0.151864,  0.174816,
          0.148918,  0.142359,  0.106548,  0.071935,  0.057695],
        [ 0.077497,  0.100954,  0.129938,  0.161939,  0.166117,  0.17732 ,
          0.132083,  0.132733,  0.0994  ,  0.062541,  0.078473],
        [ 0.092995,  0.117648,  0.120398,  0.138454,  0.153209,  0.139638,
          0.122982,  0.115096,  0.085108,  0.06125 ,  0.056625],
        [ 0.07513 ,  0.097616,  0.103521,  0.109681,  0.12434 ,  0.10906 ,
          0.100239,  0.071522,  0.077146,  0.056189,  0.06953 ]]])
```

Note, on single dimensional datasets (e.g. axes), it works as expected

WORKAROUND:
adding in `[:]` first, and using the slice on a bare numpy array works:

```
>>> dat.signal_diff[:][5]
[slice(None, None, None)]
[slice(None, None, None), slice(None, None, None)]
[slice(None, None, None), slice(None, None, None), slice(None, None, None)]
array([[ 0.009239,  0.004176,  0.013995,  0.019234,  0.032105,  0.028571,
         0.057538,  0.067145,  0.053892,  0.035661,  0.038108],
       [ 0.006867,  0.012266,  0.013482,  0.022586,  0.034085,  0.049813,
         0.050865,  0.061698,  0.046345,  0.034705,  0.034251],
       [ 0.008093,  0.009485,  0.019699,  0.045316,  0.042605,  0.066759,
         0.068236,  0.061194,  0.056653,  0.044821,  0.034751],
       [ 0.011175,  0.01587 ,  0.032948,  0.042902,  0.058639,  0.081957,
         0.082119,  0.077104,  0.070681,  0.041672,  0.034173],
       [ 0.018048,  0.031793,  0.04394 ,  0.055542,  0.089813,  0.099888,
         0.099856,  0.097067,  0.079357,  0.05533 ,  0.049295],
       [ 0.029058,  0.041938,  0.071855,  0.0942  ,  0.13493 ,  0.149842,
         0.121066,  0.106902,  0.087081,  0.076938,  0.054789],
       [ 0.045941,  0.062734,  0.101896,  0.125014,  0.164143,  0.16488 ,
         0.159616,  0.126791,  0.105373,  0.084804,  0.065533],
       [ 0.069778,  0.0903  ,  0.113436,  0.152228,  0.151864,  0.174816,
         0.148918,  0.142359,  0.106548,  0.071935,  0.057695],
       [ 0.077497,  0.100954,  0.129938,  0.161939,  0.166117,  0.17732 ,
         0.132083,  0.132733,  0.0994  ,  0.062541,  0.078473],
       [ 0.092995,  0.117648,  0.120398,  0.138454,  0.153209,  0.139638,
         0.122982,  0.115096,  0.085108,  0.06125 ,  0.056625],
       [ 0.07513 ,  0.097616,  0.103521,  0.109681,  0.12434 ,  0.10906 ,
         0.100239,  0.071522,  0.077146,  0.056189,  0.06953 ]])
```

Note that this also prevents you from being able to pick out a single value and get it returned as a number rather than an array

**Comment by ksunden** [comment]
I'd need to test this again, but I suspect this is fixed because transposition was removed

**Comment by untzag** [comment]
I agree, I think this issue is fixed
