### ISSUE TITLE
Creat_collection should handle posix path arguments

### ISSUE THREAD

**Issue by ksunden** [wright-group/WrightTools#535]
```
>>> d = wt.Collection()
>>> d.create_collection('path/to/collection')
<WrightTools.Collection 'path/to/collection' () at /tmp/cynpj247.wt5::/path/to/collection>
>>> d
<WrightTools.Collection 'collection' ('path/to/collection',) at /tmp/cynpj247.wt5::/>
>>> d.path/to/collection
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    d.path/to/collection
NameError: name 'to' is not defined
>>> d['path/to/collection']
<WrightTools.Collection 'path/to/collection' () at /tmp/cynpj247.wt5::/path/to/collection>
>>> d['path']
<HDF5 group "/path" (1 members)>
>>> d['path']['to']
<HDF5 group "/path/to" (1 members)>
>>> d['path']['to']['collection']
<HDF5 group "/path/to/collection" (0 members)>
>>> d.path
<HDF5 group "/path" (1 members)>
>>> d.path.to
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    d.path.to
AttributeError: 'Group' object has no attribute 'to'
>>> d.name
'/'
>>> d.path
<HDF5 group "/path" (1 members)>
>>> d.item_names
('path/to/collection',)
>>> collection.print_tree()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    collection.print_tree()
NameError: name 'collection' is not defined
>>> d.print_tree()
collection (/tmp/cynpj247.wt5)
└── 0: path/to/collection
>>> h5py.open('test.h5')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    h5py.open('test.h5')
AttributeError: module 'h5py' has no attribute 'open'
>>> f = h5py.File('test.h5')
>>> f.create_group('path/to/group')
<HDF5 group "/path/to/group" (0 members)>
>>> f.items()
ItemsViewHDF5(<HDF5 file "test.h5" (mode r+)>)
>>> list(f.items())
[('path', <HDF5 group "/path" (1 members)>)]
>>> 
```

**Comment by untzag** [comment]
two problems:

1) items list not made properly

2) intermediate groups created as Groups, not Collections

**Comment by ksunden** [comment]
Probably also applies to create_data (though that may be fixed via the same means)

**Comment by ksunden** [comment]
Similar, but opposite problem when defining channels/variables with "/" in them, should be converted to `__d__`, I think In that case (if people want arbitrary HDF groups/datasets as metadata, I won't enforce that they can't, but I also think that is discouraged (outside of `attrs`, It is their responsibility to ensure clashes do not happen, and when creating channels/variables from our defined methods, we should ensure that exactly one hdf object is created, and it is our own kind)
