### ISSUE TITLE
from_PyCMDS fails when centers arrays are greater than 1D

### ISSUE THREAD

**Issue by darienmorrow** [wright-group/WrightTools#701]
```
  File "/home/darien/source/WrightTools/WrightTools/data/_pycmds.py", line 97, in from_PyCMDS
    name=ax["name"] + "_centers", values=np.array(ax["centers"]).reshape(sh)

ValueError: cannot reshape array of size 11 into shape (1,21,1)
```
[000.data.zip](https://github.com/wright-group/WrightTools/files/2263445/000.data.zip)

**Comment by ksunden** [comment]
Problems may not be limited to such cases...

from_PyCMDS failed to read Autotune data

Currently hacking on wright-group/attune#11

test script for wt2:

```python
import numpy as np
from matplotlib import pyplot as plt
import WrightTools as wt

d = wt.data.from_PyCMDS("bbo.data")
c = wt.tuning.curve.from_800_curve("old.curve")
m = wt.fit.Moments()
#f = wt.fit.Fitter(m, d, "wm")
#d.transpose()
wt.tuning.workup.intensity(d,c,"pyro3")
```

Non-functioning equivalent in wt3/attune:
```pythonimport numpy as np
from matplotlib import pyplot as plt
import WrightTools as wt
import attune

d = wt.data.from_PyCMDS("bbo.data")
c = attune.curve.from_800_curve("old.curve")
m = attune.fit.Moments()
f = attune.fit.Fitter(m, d, "w3")
attune.workup.intensity(d,c,"pyro3")
```

[attune.tar.gz](https://github.com/wright-group/WrightTools/files/2288743/attune.tar.gz)

**Comment by ksunden** [comment]
The above fails due to:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    d = wt.data.from_PyCMDS("bbo.data")
  File "/home/kyle/venvs/source/WrightTools/WrightTools/data/_pycmds.py", line 154, in from_PyCMDS
    values[np.isnan(values)] = points[np.isnan(values)]
IndexError: boolean index did not match indexed array along dimension 1; dimension is 21 but corresponding boolean dimension is 1
```
Very possible the fix is the same (or at least similar) despite the fact that they cause different errors, both have to do with the shapes of the centers arrays.

This one may be able to benefit from the `mask_reduce` introduced with `split`(#698)

**Comment by ksunden** [comment]
Note: should be pyro2 above, not pyro3
 (Not that that matters for the reading in)

**Comment by ksunden** [comment]
Turned out to be a problem in a different part of the method.
